name: Build and relase

on:
  push:
    tags:
      - 'v*'

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Echo version
        run: echo ${GITHUB_REF##*/}
      - name: Build win zip
        run: ./gradlew distZip -PprojVersion=${GITHUB_REF##*/} -PjavafxPlatform=win
      - name: Build linux zip
        run: ./gradlew distZip -PprojVersion=${GITHUB_REF##*/} -PjavafxPlatform=linux
      - name: Build mac zip
        run: ./gradlew distZip -PprojVersion=${GITHUB_REF##*/} -PjavafxPlatform=mac && ls ./build/distributions
