name: Java docs test

on: [pull_request]

jobs:
  docs:

    runs-on: ubuntu-latest
    container: adoptopenjdk:11-hotspot
    steps:
      - uses: actions/checkout@v1
      - name: Docs with gradle
        run: ./gradlew javadoc
