name: Java docs deploy to gh-pages

on:
  push:
    branches:
      - master
      - docs-test

jobs:
  docs:
    runs-on: ubuntu-latest
    container: adoptopenjdk:11-hotspot
    steps:
      - uses: actions/checkout@v1
      - name: Docs with gradle
        run: ./gradlew javadoc
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/docs/javadoc # The folder the action should deploy.
