name: Gradle Test

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    container: adoptopenjdk:11-hotspot
    steps:
      - uses: actions/checkout@v1
      - name: install xvfb
        run: |
        sudo apt-get update
        sudo apt-get install xvfb
      - name: Build with Gradle
        run: xvfb-run ./gradlew test
      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1